[main]
priority = 2001
output = "example-output.tf"

[zscaler.zpa]
enabled = true
url = "https://api.config.zscaler.com/zscaler.net/zpa/json"

[zscaler.hub]
enabled = true
url = "https://config.zscaler.com/api/zscaler.net/hubs/cidr/json/recommended"

[zscaler.custom]
enabled = false

[resources]
rgNameTf = "sase-dev-vnet"
nsgNameTf = "sase-dev-whitelist"
nsgNameAz = "nsg_restrict_outbound_zscaler"