# Terraform code generated by zscaler-nsg-tool
resource "azurerm_network_security_group" "restrict_zscaler" {
  name                = "nsg_restrict_outbound_zscaler"
  location            = data.azurerm_resource_group.playground.location
  resource_group_name = data.azurerm_resource_group.playground.name

  dynamic "security_rule" {
    for_each = var.restrict_zscaler
    content {
      name                         = security_rule.value.name
      priority                     = security_rule.value.priority
      direction                    = security_rule.value.direction
      access                       = security_rule.value.access
      protocol                     = security_rule.value.protocol
      source_port_range            = security_rule.value.source_port_range
      destination_port_range       = security_rule.value.destination_port_range
      source_address_prefix        = security_rule.value.source_address_prefix
      destination_address_prefixes = security_rule.value.destination_address_prefixes
    }
  }

  security_rule {
    name                       = "DenyInternetOutbound"
    priority                   = 4001
    direction                  = "Outbound"
    access                     = "Deny"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "Internet"
    }

}
